const gardenSuppliesData = {
  tools: [
    { id: 'tools-1', name: 'Hand Trowel', price: '60 EGP', image: '/images/garden supplies/Hand Trowel.jpeg', description: 'A sturdy and essential hand tool for digging, planting, and transplanting small plants.' },
    { id: 'tools-2', name: 'Pruning Shears', price: '95 EGP', image: '/images/garden supplies/pruning shears.jpeg', description: 'Sharp and durable shears for precise trimming and cutting of branches and stems.' },
    { id: 'tools-3', name: 'Garden Fork', price: '80 EGP', image: '/images/garden supplies/fork.jpeg', description: 'A versatile tool with strong tines for aerating soil, turning compost, and loosening compacted earth.' },
    { id: 'tools-4', name: 'Watering Can', price: '120 EGP', image: '/images/garden supplies/water cane.jpeg', description: 'A classic watering can with a comfortable handle and spout for gentle and even watering of plants.' },
    { id: 'tools-5', name: 'Garden Hoe', price: '110 EGP', image: '/images/garden supplies/hoe.jpeg', description: 'A fundamental tool for weeding, cultivating soil, and preparing garden beds with ease.' },
    { id: 'tools-6', name: 'Transplanter Tool', price: '70 EGP', image: '/images/garden supplies/transplanter.jpeg', description: 'A specialized tool designed for easily digging and transferring seedlings and small plants without damage.' },
    { id: 'tools-7', name: 'Hand Cultivator', price: '65 EGP', image: '/images/garden supplies/cultivator.jpg', description: 'A small hand tool with claws for loosening soil, weeding, and aerating around plants.' },
    { id: 'tools-8', name: 'Weeding Tool', price: '75 EGP', image: '/images/garden supplies/weeding tool.jpg', description: 'A specialized tool for effective removal of weeds from roots, keeping your garden neat.' },
    { id: 'tools-9', name: 'Garden Rake', price: '150 EGP', image: '/images/garden supplies/rake.jpg', description: 'A durable rake for leveling soil, clearing debris, and preparing large garden areas.' },
    { id: 'tools-10', name: 'Dibber', price: '55 EGP', image: '/images/garden supplies/dibber.jpg', description: 'A pointed tool for making holes in the soil for planting seeds or small bulbs.' },
    { id: 'tools-11', name: 'Leaf Blower (Electric)', price: '450 EGP', image: '/images/garden supplies/leaf blower.jpg', description: 'An electric leaf blower for quickly clearing leaves and debris from lawns and pathways.' }, 
    { id: 'tools-12', name: 'Bypass Loppers', price: '180 EGP', image: '/images/garden supplies/bybass.jpg', description: 'Long-handled pruning tool for cutting thicker branches with less effort.' },
  ],
  soilAndFertilizer: [
    { id: 'soilAndFertilizer-1', name: 'Potting Soil Mix (5kg)', price: '50 EGP', image: '/images/garden supplies/soil mix.jpeg', description: 'A premium blend of potting soil, ideal for promoting healthy growth in potted plants.' },
    { id: 'soilAndFertilizer-2', name: 'Compost Organic Fertilizer', price: '90 EGP', image: '/images/garden supplies/organic fertilizer.jpeg', description: 'Rich, organic compost that enriches soil, provides essential nutrients, and improves plant vitality.' },
    { id: 'soilAndFertilizer-3', name: 'Cactus Soil Mix', price: '60 EGP', image: '/images/garden supplies/cactus mix.jpeg', description: 'A specially formulated soil mix with excellent drainage, perfect for cacti, succulents, and other drought-loving plants.' },
    { id: 'soilAndFertilizer-4', name: 'Liquid Plant Food', price: '75 EGP', image: '/images/garden supplies/liquid mix.jpeg', description: 'A concentrated liquid fertilizer that provides a quick boost of nutrients for lush foliage and abundant blooms.' },
    { id: 'soilAndFertilizer-5', name: 'Peat Moss (Compressed)', price: '85 EGP', image: '/images/garden supplies/peat moss (1).jpeg', description: 'Compressed peat moss, an excellent soil amendment for improving moisture retention and aeration in garden beds.' },
    { id: 'soilAndFertilizer-6', name: 'Bone Meal Fertilizer', price: '95 EGP', image: '/images/garden supplies/bone meal.jpeg', description: 'An organic slow-release fertilizer rich in phosphorus and calcium, promoting strong root development and flowering.' },
    { id: 'soilAndFertilizer-7', name: 'Vermiculite (2L)', price: '45 EGP', image: '/images/garden supplies/Vermiculite.jpg', description: 'Lightweight mineral that improves soil aeration and moisture retention, ideal for seed starting.' },
    { id: 'soilAndFertilizer-8', name: 'Perlite (3L)', price: '40 EGP', image: '/images/garden supplies/perlite.jpg', description: 'Volcanic rock that enhances drainage and aeration in potting mixes, preventing compaction.' },
    { id: 'soilAndFertilizer-9', name: 'All-Purpose Granular Fertilizer', price: '110 EGP', image: '/images/garden supplies/all purpose mix.jpg', description: 'Balanced slow-release granular fertilizer for general garden use, providing steady nutrition.' },
    { id: 'soilAndFertilizer-10', name: 'Orchid Potting Mix', price: '70 EGP', image: '/images/garden supplies/orchid mix.jpg', description: 'Specialized bark-based mix for orchids, ensuring excellent drainage and air circulation for healthy roots.' },
    { id: 'soilAndFertilizer-11', name: 'Seed Starting Mix', price: '60 EGP', image: '/images/garden supplies/seed mix.jpg', description: 'Fine-textured, sterile mix for germinating seeds, providing an optimal environment for sprouts.' },
    { id: 'soilAndFertilizer-12', name: 'Worm Castings (Organic)', price: '120 EGP', image: '/images/garden supplies/Earthworm Castings.jpg', description: 'Highly beneficial organic fertilizer, rich in microbes and nutrients for vigorous plant growth.' },
  ],
  accessories: [
    { id: 'accessories-1', name: 'Plant Labels Pack', price: '25 EGP', image: '/images/garden supplies/labels.jpeg', description: 'A pack of durable plant labels for easy identification of your herbs, vegetables, and flowers.' },
    { id: 'accessories-2', name: 'Garden Gloves', price: '40 EGP', image: '/images/garden supplies/gloves.jpeg', description: 'Comfortable and protective garden gloves, essential for keeping your hands clean and safe while gardening.' },
    { id: 'accessories-3', name: 'Hanging Hooks Set', price: '35 EGP', image: '/images/garden supplies/hooks (1).jpeg', description: 'A set of sturdy hooks for hanging baskets, bird feeders, or other garden decorations.' },
    { id: 'accessories-4', name: 'Plant Ties Roll', price: '30 EGP', image: '/images/garden supplies/plant tie roll.jpeg', description: 'A convenient roll of soft plant ties for supporting climbing plants and securing stems.' },
    { id: 'accessories-5', name: 'Spray Bottle (1L)', price: '45 EGP', image: '/images/garden supplies/spray bottle.jpeg', description: 'A versatile spray bottle for misting plants, applying foliar feeds, or pest control solutions.' },
    { id: 'accessories-6', name: 'Mini Greenhouse Cover', price: '100 EGP', image: '/images/garden supplies/greenhouse cover.jpeg', description: 'A protective cover for mini greenhouses, creating an ideal environment for seed starting and plant propagation.' },
    { id: 'accessories-7', name: 'Garden Kneeler', price: '80 EGP', image: '/images/garden supplies/garden knealer.jpg', description: 'A comfortable padded kneeler to protect your knees while working in the garden.' },
    { id: 'accessories-8', name: 'Garden Tool Belt', price: '90 EGP', image: '/images/garden supplies/tool belt.jpg', description: 'A practical belt with multiple pockets for keeping essential garden tools close at hand.' },
    { id: 'accessories-9', name: 'Potting Mat', price: '60 EGP', image: '/images/garden supplies/potting mat.jpg', description: 'A waterproof mat for containing soil and mess during potting and transplanting tasks.' },
    { id: 'accessories-10', name: 'Plant Mister (Brass)', price: '110 EGP', image: '/images/garden supplies/mister.jpg', description: 'An elegant brass plant mister, perfect for providing humidity to delicate plants.' },
    { id: 'accessories-11', name: 'Seed Dispenser', price: '30 EGP', image: '/images/garden supplies/seed dispenser.jpg', description: 'A small tool for accurately dispensing tiny seeds, preventing overcrowding.' },
    { id: 'accessories-12', name: 'Twist Tie Cutter', price: '20 EGP', image: '/images/garden supplies/Twist Tie Cutter.jpg', description: 'A convenient tool for quickly cutting and dispensing garden twist ties from a roll.' },
  ],
  irrigation: [
    { id: 'irrigation-1', name: 'Drip Irrigation Kit', price: '180 EGP', image: '/images/garden supplies/irrigation kit.jpeg', description: 'An efficient drip irrigation kit for targeted watering, conserving water and promoting healthy plant growth.' },
    { id: 'irrigation-2', name: 'Soaker Hose (10m)', price: '140 EGP', image: '/images/garden supplies/hose.jpeg', description: 'A porous soaker hose that delivers water directly to the root zone, reducing evaporation and runoff.' },
    { id: 'irrigation-3', name: 'Automatic Water Timer', price: '250 EGP', image: '/images/garden supplies/water timer (1).jpeg', description: 'A programmable automatic water timer for hands-free watering, ensuring your plants receive consistent hydration.' },
    { id: 'irrigation-4', name: 'Sprinkler Head Set', price: '130 EGP', image: '/images/garden supplies/sprinkler.jpeg', description: 'A set of adjustable sprinkler heads for even and widespread watering of lawns and garden beds.' },
    { id: 'irrigation-5', name: 'Irrigation Pipe Roll', price: '160 EGP', image: '/images/garden supplies/pipes.jpeg', description: 'A roll of durable irrigation piping for setting up custom watering systems in your garden.' },
    { id: 'irrigation-6', name: 'Watering Wand', price: '120 EGP', image: '/images/garden supplies/water wand.jpeg', description: 'A long watering wand with multiple spray patterns for reaching hanging baskets and delicate plants with ease.' },
    { id: 'irrigation-7', name: 'Rain Barrel Diverter Kit', price: '220 EGP', image: '/images/garden supplies/Raincatcher Kit.jpg', description: 'Kit for connecting a rain barrel to your downspout, allowing you to collect and reuse rainwater.' },
    { id: 'irrigation-8', name: 'Garden Hose Nozzle (Multi-Pattern)', price: '90 EGP', image: '/images/garden supplies/Water Hose Gun.jpg', description: 'Adjustable hose nozzle with various spray patterns for versatile watering needs.' },
    { id: 'irrigation-9', name: 'Capillary Matting (Per Meter)', price: '70 EGP', image: '/images/garden supplies/Water Capillary Mats.jpg', description: 'Absorbent matting for bottom watering pots, ensuring consistent moisture for seedlings and sensitive plants.' },
    { id: 'irrigation-10', name: 'Soil Moisture Meter', price: '85 EGP', image: '/images/garden supplies/Soil Moisture Meter.jpg', description: 'A simple tool to measure soil moisture levels, helping you water your plants accurately.' },
    { id: 'irrigation-11', name: 'Micro Drip Emitters Pack', price: '60 EGP', image: '/images/garden supplies/Micro Drip Irrigation.jpg', description: 'Pack of micro drip emitters for precise, low-volume watering in drip irrigation systems.' },
    { id: 'irrigation-12', name: 'Garden Hose Quick Connectors', price: '50 EGP', image: '/images/garden supplies/hose conncetors.jpg', description: 'Set of quick connectors for easily attaching and detaching garden hoses and accessories.' },
  ],
  pestControl: [
    { id: 'pestControl-1', name: 'Neem Oil Spray', price: '90 EGP', image: '/images/garden supplies/The Plant Runner Neem Oil.jpeg', description: 'An organic and effective neem oil spray for naturally controlling a wide range of common garden pests.' },
    { id: 'pestControl-2', name: 'Sticky Traps Pack', price: '35 EGP', image: '/images/garden supplies/sticky traps.jpeg', description: 'A pack of yellow sticky traps, highly effective for monitoring and trapping flying insects in your garden.' },
    { id: 'pestControl-3', name: 'Organic Insecticidal Soap', price: '85 EGP', image: '/images/garden supplies/insect soap.jpeg', description: 'A gentle yet powerful organic insecticidal soap for safely eliminating soft-bodied insects on plants.' },
    { id: 'pestControl-4', name: 'Ant Barrier Powder', price: '50 EGP', image: '/images/garden supplies/ant powder.jpeg', description: 'An effective barrier powder designed to deter ants from entering your home and garden areas.' },
    { id: 'pestControl-5', name: 'Snail and Slug Pellets', price: '65 EGP', image: '/images/garden supplies/Defenders Slugs Away® Wool Pellets - 10L _ Natural & Biodegradable Slug and Snail Deterrent _ Safe for Gardens, Plants & Wildlife _ Eco-Friendly Mulch _ Effective Moisture Retention & Pest Control.jpeg', description: 'Eco-friendly pellets that safely deter snails and slugs, protecting your plants from damage.' },
    { id: 'pestControl-6', name: 'Mosquito Repellent Coil (Garden Use)', price: '40 EGP', image: '/images/garden supplies/mosquito coils.jpeg', description: 'Mosquito repellent coils designed for outdoor garden use, providing effective protection against biting insects.' },
    { id: 'pestControl-7', name: 'Diatomaceous Earth (Food Grade)', price: '75 EGP', image: '/images/garden supplies/Diatomaceous Earth.jpg', description: 'Natural, non-toxic powder for controlling crawling insects by physical dehydration.' },
    { id: 'pestControl-8', name: 'Insect Netting (Per Meter)', price: '100 EGP', image: '/images/garden supplies/insect netting.jpg', description: 'Fine mesh netting to protect plants from insect pests while allowing air and light through.' },
    { id: 'pestControl-9', name: 'Ladybug Larvae (Beneficial Insects)', price: '150 EGP', image: '/images/garden supplies/lady bugs.jpg', description: 'Live ladybug larvae for natural control of aphids and other soft-bodied pests.' },
    { id: 'pestControl-10', name: 'Rodent Repellent Granules', price: '60 EGP', image: '/images/garden supplies/rodent granules.jpg', description: 'Granules that naturally deter rodents from garden areas without harm.' },
    { id: 'pestControl-11', name: 'Bird Netting (Small Roll)', price: '90 EGP', image: '/images/garden supplies/anti bird nesting.jpg', description: 'Lightweight netting to protect fruit and vegetables from bird damage.' },
    { id: 'pestControl-12', name: 'Copper Tape (Slug/Snail Barrier)', price: '55 EGP', image: '/images/garden supplies/snail copper tape.jpg', description: 'Self-adhesive copper tape creates a barrier that deters slugs and snails from pots and beds.' },
  ],
  giftBoxes: [
    { id: 'giftBoxes-1', name: 'Mini Herb Garden Kit', price: '150 EGP', image: '/images/garden supplies/herbs kit.jpeg', description: 'A charming kit containing everything needed to start a small indoor herb garden, perfect for beginners.' },
    { id: 'giftBoxes-2', name: 'Succulent Gift Box', price: '170 EGP', image: '/images/garden supplies/Succulent Gift Box.jpeg', description: 'A beautifully curated gift box featuring a selection of easy-care succulents, ideal for adding greenery to any space.' },
    { id: 'giftBoxes-3', name: 'Garden Tools Starter Set', price: '200 EGP', image: '/images/garden supplies/Gift Box - Gardener.jpeg', description: 'A comprehensive starter set of essential garden tools, perfect for aspiring gardeners.' },
    { id: 'giftBoxes-4', name: 'Flower Grow Kit with Seeds', price: '140 EGP', image: '/images/garden supplies/Flower Seed Storage Packets.jpeg', description: 'A delightful kit including seeds and all the essentials to grow beautiful flowers from scratch.' },
    { id: 'giftBoxes-5', name: 'Terracotta Pot & Soil Gift Set', price: '160 EGP', image: '/images/garden supplies/pots set.png', description: 'A thoughtful gift set featuring a classic terracotta pot and premium potting soil, ready for planting.' },
    { id: 'giftBoxes-6', name: 'Eco-Friendly Garden Gift Box', price: '180 EGP', image: '/images/garden supplies/Choose a plan.jpeg', description: 'A sustainable gift box filled with eco-friendly gardening essentials, perfect for environmentally conscious gardeners.' },
  ],
};

export default gardenSuppliesData;