const potsData = {
  ceramic: [
    { id: 'ceramic-1', name: 'White Glazed Ceramic Pot', price: '120 EGP', image: '/images/pots/white glazed ceramic pot.jpeg', description: 'A sleek and elegant pot with a smooth, glossy white finish, perfect for modern interiors.' },
    { id: 'ceramic-2', name: 'Matte Black Ceramic Planter', price: '130 EGP', image: '/images/pots/matte black pots.jpeg', description: 'A sophisticated matte black planter that provides a striking contrast for vibrant plants.' },
    { id: 'ceramic-3', name: 'Minimalist Clay Pot', price: '110 EGP', image: '/images/pots/minimalst clay pots.jpeg', description: 'A simple yet stylish clay pot with a clean design, ideal for a contemporary aesthetic.' },
    { id: 'ceramic-4', name: 'Textured Terracotta Pot', price: '125 EGP', image: '/images/pots/textured clay pots.jpeg', description: 'A classic terracotta pot featuring a unique textured surface, adding character to any plant display.' },
    { id: 'ceramic-5', name: 'Patterned Ceramic Planter', price: '140 EGP', image: '/images/pots/ceramic pattern pots.jpeg', description: 'An eye-catching ceramic planter adorned with intricate patterns, perfect for adding a decorative touch.' },
    { id: 'ceramic-6', name: 'Speckled Grey Ceramic Pot', price: '135 EGP', image: '/images/pots/Speckled White Ceramic.jpeg', description: 'A charming grey ceramic pot with subtle speckles, offering a rustic yet refined look.' },
    { id: 'ceramic-7', name: 'Glossy Blue Ceramic Pot', price: '130 EGP', image: '/images/pots/blue glazed pot.jpg', description: 'A vibrant blue ceramic pot with a high-gloss finish, perfect for adding a pop of color.' },
    { id: 'ceramic-8', name: 'Hand-Painted Floral Ceramic', price: '150 EGP', image: '/images/pots/floral pot.jpg', description: 'An exquisite ceramic pot hand-painted with delicate floral designs, ideal for a touch of artistry.' },
    { id: 'ceramic-9', name: 'Ribbed Ceramic Pot', price: '120 EGP', image: '/images/pots/ripped pot.jpg', description: 'A contemporary ceramic pot with a subtle ribbed texture, offering a modern and tactile feel.' },
    { id: 'ceramic-10', name: 'Speckled White Ceramic Pots with Feet', price: '145 EGP', image: '/images/pots/speckled pot.jpg', description: 'Adorable and stylish, these speckled white ceramic pots stand on cute little legs, perfect for your small plants.' },
    { id: 'ceramic-11', name: 'Tall Cylinder Ceramic Pot', price: '160 EGP', image: '/images/pots/The Cylinder Rooties.jpg', description: 'A sleek and tall cylindrical ceramic pot, perfect for showcasing upright plants and adding height.' },
    { id: 'ceramic-12', name: 'Earthenware Rustic Pot', price: '115 EGP', image: '/images/pots/earthy pot.jpg', description: 'A natural earthenware pot with a rustic charm, ideal for a more organic and earthy look.' },
  ],
  plastic: [
    { id: 'plastic-1', name: 'Basic Black Plastic Pot', price: '45 EGP', image: '/images/pots/Basic Black Plastic Pot.jpeg', description: 'A lightweight and durable black plastic pot, essential for everyday planting needs.' },
    { id: 'plastic-2', name: 'Colorful Plastic Planter Set', price: '75 EGP', image: '/images/pots/coloured pots.jpeg', description: 'A vibrant set of plastic planters in assorted colors, perfect for brightening up any space.' },
    { id: 'plastic-3', name: 'Plastic Pot with Saucer', price: '55 EGP', image: '/images/pots/pot with saucer.jpeg', description: 'A practical plastic pot complete with a matching saucer to catch excess water and keep surfaces clean.' },
    { id: 'plastic-4', name: 'Terracotta-Colored Pots', price: '50 EGP', image: '/images/pots/terracota-pots.webp', description: 'A lightweight plastic pot designed to mimic the classic look of terracotta, offering durability and affordability.' },
    { id: 'plastic-5', name: 'Wide Rim Plastic Planter', price: '65 EGP', image: '/images/pots/wide rim pot.jpeg', description: 'A sturdy plastic planter featuring a wide rim for easy handling and added stability.' },
    { id: 'plastic-6', name: 'Plastic Hanging Basket', price: '60 EGP', image: '/images/pots/hanging basket.jpeg', description: 'A functional plastic hanging basket, ideal for showcasing trailing plants outdoors or indoors.' },
    { id: 'plastic-7', name: 'Durable Square Plastic Pot', price: '50 EGP', image: '/images/pots/square pot.jpg', description: 'A sturdy square plastic pot, perfect for efficient space utilization and a clean look.' },
    { id: 'plastic-8', name: 'Recycled Plastic Pot', price: '70 EGP', image: '/images/pots/recycled plastic (1).jpg', description: 'An eco-friendly pot made from recycled plastic, combining sustainability with practicality.' },
    { id: 'plastic-9', name: 'Textured Grey Plastic Pot', price: '58 EGP', image: '/images/pots/textured plastic pot.jpg', description: 'A lightweight plastic pot with a subtle textured finish in grey, offering a modern aesthetic.' },
    { id: 'plastic-10', name: 'Grow Bag - Fabric Pot', price: '40 EGP', image: '/images/pots/grow bag.jpg', description: 'A breathable fabric pot ideal for root health and air pruning, promoting stronger plant growth.' },
    { id: 'plastic-11', name: 'Plastic Nursery Pot Bulk', price: '80 EGP', image: '/images/pots/nursery pot.jpg', description: 'Economical plastic nursery pots, perfect for starting seeds or transplanting seedlings.' },
    { id: 'plastic-12', name: 'Decorative Outdoor Plastic Planter', price: '120 EGP', image: '/images/pots/outdoor planter.jpg', description: 'A larger, decorative plastic planter suitable for outdoor use, adding charm to patios or gardens.' },
  ],
  hanging: [
    { id: 'hanging-1', name: 'Macrame Hanging Pot', price: '200 EGP', image: '/images/pots/Macrame Hanging Pot.jpeg', description: 'A stylish hanging pot nestled in a beautiful handcrafted macrame hanger, perfect for a bohemian touch.' },
    { id: 'hanging-2', name: 'Woven Hanging Basket', price: '110 EGP', image: '/images/pots/Woven Hanging Basket.jpeg', description: 'A charming woven basket designed for hanging, bringing a natural and rustic feel to your decor.' },
    { id: 'hanging-3', name: 'Terracotta Hanging Planter', price: '115 EGP', image: '/images/pots/Terracotta Hanging Planter.jpeg', description: 'A classic terracotta pot designed for hanging, offering excellent drainage and an earthy aesthetic.' },
    { id: 'hanging-4', name: 'Metal Wall-Mount Planter', price: '130 EGP', image: '/images/pots/Metal Wall-Mount Planter (1).jpeg', description: 'A sleek metal planter designed to be mounted on a wall, ideal for saving space and creating vertical gardens.' },
    { id: 'hanging-5', name: 'Ceramic Hanging Pot', price: '125 EGP', image: '/images/pots/Ceramic Hanging Pot.jpeg', description: 'An elegant ceramic pot with integrated hanging capabilities, adding a touch of sophistication to your suspended plants.' },
    { id: 'hanging-6', name: 'Double Tier Hanging Basket', price: '140 EGP', image: '/images/pots/Double Tier Hanging Basket.jpeg', description: 'A unique two-tiered hanging basket, allowing you to display multiple plants in a compact vertical arrangement.' },
    { id: 'hanging-7', name: 'Coconut Fiber Hanging Liner', price: '70 EGP', image: '/images/pots/coconut pot.jpg', description: 'A natural coconut fiber liner for hanging baskets, promoting aeration and drainage for healthy roots.' },
    { id: 'hanging-8', name: 'Modern Geometric Hanging Planter', price: '105 EGP', image: '/images/pots/geometric.jpg', description: 'A contemporary hanging planter with a sharp geometric design, ideal for a minimalist aesthetic.' },
    { id: 'hanging-9', name: 'Glass Globe Terrarium Hanger', price: '135 EGP', image: '/images/pots/glass globe.jpg', description: 'A unique glass globe perfect for small terrariums or air plants, designed for hanging display.' },
    { id: 'hanging-10', name: 'Adjustable Rope Hanging Pot', price: '95 EGP', image: '/images/pots/rope pot.jpg', description: 'A versatile pot with an adjustable rope hanger, allowing for flexible display heights.' },
    { id: 'hanging-11', name: 'Tiered Metal Hanging Planter', price: '155 EGP', image: '/images/pots/tiered planter.jpg', description: 'A stylish tiered metal hanging planter, offering multiple levels for plant display in a compact form.' },
    { id: 'hanging-12', name: 'Birdcage Style Hanging Planter', price: '165 EGP', image: '/images/pots/bird cage.jpg', description: 'An ornate birdcage-inspired hanging planter, adding a vintage and whimsical touch.' },
  ],
  selfWatering: [
    { id: 'selfWatering-1', name: 'Self-Watering Pot - Small', price: '95 EGP', image: '/images/pots/Self-Watering Pot - Small.jpeg', description: 'A convenient small self-watering pot, perfect for busy plant owners ensuring consistent moisture.' },
    { id: 'selfWatering-2', name: 'Smart Watering Pot - Medium', price: '135 EGP', image: '/images/pots/Smart Watering Pot - Medium.jpeg', description: 'A medium-sized smart watering pot with an efficient system to keep your plants perfectly hydrated.' },
    { id: 'selfWatering-3', name: 'Large Self-Watering Planter', price: '180 EGP', image: '/images/pots/Large Self-Watering Planter.jpeg', description: 'A spacious self-watering planter ideal for larger plants, reducing the frequency of watering.' },
    { id: 'selfWatering-4', name: 'Terracotta Self-Watering Pot', price: '160 EGP', image: '/images/pots/Terracotta Self-Watering Pot.jpeg', description: 'A self-watering pot made from breathable terracotta, combining traditional aesthetics with modern convenience.' },
    { id: 'selfWatering-5', name: 'Transparent Water Level Pot', price: '145 EGP', image: '/images/pots/Transparent Water Level Pot.jpeg', description: 'A self-watering pot with a clear indicator for water levels, allowing you to easily monitor your plant\'s hydration.' },
    { id: 'selfWatering-6', name: 'self-care planter', price: '150 EGP', image: '/images/pots/Self-Care Self-Watering Planter.jpeg', description: 'A thoughtfully designed self-watering planter that simplifies plant care, perfect for those new to gardening.' },
    { id: 'selfWatering-8', name: 'Hydroponic Self-Watering Unit', price: '220 EGP', image: '/images/pots/Hydroponic.jpg', description: 'An advanced self-watering system ideal for hydroponic gardening, ensuring precise nutrient delivery.' },
    { id: 'selfWatering-9', name: 'Decorative Self-Watering pot', price: '190 EGP', image: '/images/pots/decorative planter.jpg', description: 'A decorative self-watering urn, combining elegant design with the convenience of automated watering.' },
    { id: 'selfWatering-12', name: 'Mini Greenhouse Self-Watering', price: '200 EGP', image: '/images/pots/greenhouse.jpg', description: 'A compact self-watering unit integrated with a mini greenhouse, ideal for nurturing seedlings.' },
  ],
  decorative: [
    { id: 'decorative-1', name: 'Face Design Ceramic Planter', price: '155 EGP', image: '/images/pots/Face Design Ceramic Planter.jpeg', description: 'A unique ceramic planter featuring a sculpted face design, adding a whimsical and artistic touch to your decor.' },
    { id: 'decorative-2', name: 'Boho Pattern Planter', price: '160 EGP', image: '/images/pots/Boho Pattern Planter.jpeg', description: 'A stylish planter adorned with intricate bohemian patterns, perfect for adding an eclectic vibe to your space.' },
    { id: 'decorative-3', name: 'Animal Shaped Pot', price: '140 EGP', image: '/images/pots/animal shaped pot.jpeg', description: 'A fun and quirky pot shaped like an animal, ideal for adding personality and charm to a child\'s room or playful decor.' },
    { id: 'decorative-4', name: 'Terracotta Owl Pot', price: '135 EGP', image: '/images/pots/Terracotta Owl Pot.jpeg', description: 'A cute terracotta pot sculpted into an owl shape, bringing a touch of nature-inspired whimsy to your plant display.' },
    { id: 'decorative-5', name: 'Geometric Concrete Pot', price: '150 EGP', image: '/images/pots/geometric pots.jpeg', description: 'A modern concrete pot with a sharp geometric design, perfect for contemporary and industrial interior styles.' },
    { id: 'decorative-6', name: 'Color Splash Painted Pot', price: '145 EGP', image: '/images/pots/Color Splash Painted Pot.jpeg', description: 'A vibrant pot featuring an abstract color splash design, adding a burst of artistic flair to your plant collection.' },
    { id: 'decorative-7', name: 'Marble Effect Ceramic Pot', price: '170 EGP', image: '/images/pots/marble pots.jpg', description: 'An elegant ceramic pot with a sophisticated marble effect finish, perfect for luxurious interiors.' },
    { id: 'decorative-8', name: 'Zen Garden Stone Planter', price: '180 EGP', image: '/images/pots/zen garden pots.jpg', description: 'A calming stone planter designed for mini zen gardens, fostering tranquility and minimalist beauty.' },
    { id: 'decorative-9', name: 'Mosaic Tiled Planter', price: '195 EGP', image: '/images/pots/mosaic pot.jpg', description: 'A stunning planter adorned with colorful mosaic tiles, creating a vibrant and unique focal point.' },
    { id: 'decorative-10', name: 'Vintage Inspired bucket Pot', price: '165 EGP', image: '/images/pots/vintage pot.jpg', description: 'A charming bucket pot with a vintage design, adding nostalgic character to your plant display.' },
    { id: 'decorative-11', name: 'Textured Gold Accent Planter', price: '210 EGP', image: '/images/pots/gold pot.jpg', description: 'A lavish planter with a textured finish and elegant gold accents, exuding luxury and style.' },
    { id: 'decorative-12', name: 'Figurative Art Planter', price: '200 EGP', image: '/images/pots/figurative pot (1).jpg', description: 'A unique planter sculpted into a human figure, serving as a striking piece of art and decor.' },
  ],
};

export default potsData;